# This section will create a secret in the Kubernetes cluster.
# We need this for private docker repos.
apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: DOCKER_CONFIG
type: kubernetes.io/dockerconfigjson
---
# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: steve-deploy
  labels:
    app: steve-app
spec:
  selector:
    matchLabels:
      app: steve-app
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: steve-app
    spec:
      containers:
      - name: steve-app
        image: DOCKERHUB_USERNAME/DOCKERHUB_REPOSITORY:IMAGE_LABEL
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
      - name: beyond-api
        image: DOCKERHUB_USERNAME/dnd-beyond-pdf-parser:1.0.0
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
